@extends('layouts.app')
@section('title', 'Nosotros | JV Ropa Típica')
@section('description', 'Conoce la historia de JV Ropa Típica y nuestro compromiso con la tradición yucateca.')
@section('content')
<section class="pt-20"><div class="grid min-h-[78vh] lg:grid-cols-2"><div class="flex items-center bg-warm px-5 py-20 sm:px-10 lg:px-16 xl:px-24"><div class="reveal"><p class="eyebrow">{{ $section?->subtitle ?? 'Nuestra historia' }}</p><h1 class="display-xl mt-7">{{ $section?->title ?? 'Nuestra historia también se viste.' }}</h1></div></div><div class="image-reveal min-h-[55vh]"><img src="{{ $section?->image ?? '/images/editorial/patio-yucateco.jpg' }}" alt="Patio yucateco, origen de JV Ropa Típica" class="h-full w-full object-cover" width="900" height="1100"></div></div></section>
<section class="section-pad"><div class="shell grid gap-12 lg:grid-cols-12"><p class="eyebrow lg:col-span-2">JV · Tekit</p><div class="lg:col-span-6"><p class="font-display text-[clamp(2rem,3.5vw,3.5rem)] leading-[1.08]">Una forma de vestir que conecta origen, oficio y vida cotidiana.</p><p class="copy mt-9">{{ $section?->content }}</p></div><div class="lg:col-span-3 lg:col-start-10 lg:pt-24"><div class="border-t border-ink pt-5 text-sm leading-7"><p class="eyebrow mb-4">Lo que nos guía</p><p>Tradición sin nostalgia.</p><p>Calidad que se percibe.</p><p>Atención cercana.</p><p>Fabricación local.</p></div></div></div></section>
<section class="bg-ink py-8"><div class="shell grid items-center gap-10 text-white lg:grid-cols-2"><div class="image-reveal aspect-[4/3] overflow-hidden"><img src="/images/editorial/artesania.jpg" alt="Trabajo artesanal en una prenda" loading="lazy" class="h-full w-full object-cover" width="800" height="600"></div><div class="reveal py-12 lg:px-14"><p class="eyebrow !text-silver">Hecho aquí</p><h2 class="display-lg mt-6">El detalle también cuenta una historia.</h2><p class="mt-7 max-w-lg text-sm leading-7 text-white/60">Cada textura, pliegue y bordado forma parte de una tradición viva. Elegimos prendas pensadas para durar y sentirse propias.</p></div></div></section>
<x-catalog-cta />
@endsection
