@extends('layouts.app')
@section('title', 'Contacto y envíos | JV Ropa Típica')
@section('description', 'Contacta a JV Ropa Típica por WhatsApp. Envíos desde Tekit, Yucatán, a toda la República Mexicana.')
@section('content')
@php
    $whatsapp = $siteSettings->get('whatsapp', '5219999085831');
    $message = urlencode('Hola, encontré JV Ropa Típica en su página web y quisiera recibir información sobre modelos, tallas y envíos.');
@endphp
<section class="bg-warm pb-20 pt-36 md:pb-28 md:pt-44"><div class="shell grid gap-12 lg:grid-cols-2"><div><p class="eyebrow">Hablemos</p><h1 class="display-xl mt-6">Estamos para<br><span class="italic">orientarte.</span></h1></div><div class="self-end"><p class="copy max-w-lg">Cuéntanos qué prenda buscas. Te ayudamos a revisar modelos, disponibilidad, tallas, colores y opciones de envío.</p><a href="https://wa.me/{{ $whatsapp }}?text={{ $message }}" target="_blank" rel="noopener" class="btn-dark mt-8 w-full sm:w-auto">Escribir por WhatsApp →</a></div></div></section>
<section class="py-16 md:py-24"><div class="shell grid gap-10 md:grid-cols-3">@foreach([['Atención','WhatsApp','999 908 5831'],['Origen','Taller y atención','Tekit, Yucatán'],['Cobertura','Paquetería nacional','Todo México']] as $item)<div class="reveal border-t border-ink pt-6"><p class="eyebrow">{{ $item[0] }}</p><h2 class="mt-5 font-sans text-lg font-medium">{{ $item[1] }}</h2><p class="mt-2 text-sm text-muted">{{ $item[2] }}</p></div>@endforeach</div></section>
<section id="preguntas" class="border-t border-line section-pad"><div class="shell grid gap-12 lg:grid-cols-[.7fr_1.3fr]"><div><p class="eyebrow">Antes de escribirnos</p><h2 class="display-md mt-5">Preguntas frecuentes</h2></div><div x-data="{ open: 0 }" class="border-t border-ink">@foreach([['¿Realizan envíos a todo México?','Sí. Enviamos desde Yucatán a toda la República Mexicana. Te compartimos costo y tiempo estimado al confirmar tu código postal.'],['¿Cómo sé qué talla elegir?','Consulta nuestra guía de tallas o envíanos tus medidas por WhatsApp. Con gusto te orientamos antes de confirmar.'],['¿Todos los modelos están disponibles?','La disponibilidad cambia según modelo, talla y color. Escríbenos para confirmar o solicitar el catálogo actualizado.'],['¿Cómo se realiza el pedido?','El proceso se coordina directamente por WhatsApp: eliges la prenda, confirmamos existencia, pago y datos de envío.']] as $index=>$faq)<div class="border-b border-line"><button @click="open = open === {{ $index }} ? -1 : {{ $index }}" class="flex w-full items-center justify-between py-6 text-left text-sm font-medium"><span>{{ $faq[0] }}</span><span class="ml-5 text-xl font-light" x-text="open === {{ $index }} ? '−' : '+'"></span></button><div x-cloak x-show="open === {{ $index }}" x-transition.opacity class="pb-6 pr-10 text-sm leading-7 text-muted">{{ $faq[1] }}</div></div>@endforeach</div></div></section>
@endsection
