@extends('layouts.app')
@section('title', 'Guía de tallas | JV Ropa Típica')
@section('description', 'Consulta las medidas para guayaberas, vestidos y pantalones de JV Ropa Típica.')
@section('content')
<section class="bg-warm pb-16 pt-36 md:pb-24 md:pt-44"><div class="shell flex justify-end mb-8"><a href="{{ url()->previous() }}" class="inline-flex items-center gap-2 text-[10px] font-semibold uppercase tracking-[.15em] text-muted transition hover:text-ink"><span class="inline-block transition-transform hover:-translate-x-0.5">←</span> Volver</a></div><div class="shell grid gap-8 lg:grid-cols-2"><div><p class="eyebrow">Guía de medidas</p><h1 class="display-xl mt-6">Encuentra tu<br><span class="italic">talla ideal.</span></h1></div><p class="copy max-w-lg self-end">Toma tus medidas sin ajustar demasiado la cinta. Si estás entre dos tallas, escríbenos: te ayudaremos a elegir la mejor opción.</p></div></section>
<section class="section-pad" x-data="{ tab: 'guayaberas' }"><div class="shell">
    <div class="flex overflow-x-auto border-b border-ink" role="tablist">@foreach(['guayaberas'=>'Guayaberas','vestidos'=>'Vestidos','pantalones'=>'Pantalones'] as $key=>$label)<button @click="tab='{{ $key }}'" :class="tab==='{{ $key }}' ? 'bg-ink text-white' : 'text-muted'" class="min-w-fit px-6 py-4 text-[10px] font-semibold uppercase tracking-[.15em] sm:flex-1" role="tab">{{ $label }}</button>@endforeach</div>
    <div x-show="tab==='guayaberas'" x-transition.opacity class="pt-12">
        <div class="grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><p class="eyebrow">Cómo medir</p><h2 class="display-md mt-4">Guayaberas</h2><div class="mt-9 space-y-7 text-sm leading-6"><p><strong class="block text-[10px] uppercase tracking-[.14em]">Largo de guayabera</strong><span class="text-muted">Del punto más alto del hombro hasta la parte inferior del delantero.</span></p><p><strong class="block text-[10px] uppercase tracking-[.14em]">Pecho</strong><span class="text-muted">Circunferencia aproximadamente una pulgada debajo de la sisa.</span></p><p><strong class="block text-[10px] uppercase tracking-[.14em]">Largo de manga</strong><span class="text-muted">Del hombro hasta el puño.</span></p></div></div>
        <div class="overflow-x-auto"><table class="w-full min-w-[520px] text-left text-sm"><thead class="border-b border-ink text-[10px] uppercase tracking-[.14em]"><tr><th class="py-4">Talla</th><th>Pecho</th><th>Largo</th><th>Manga</th></tr></thead><tbody>@foreach([['34 (XS)',102,70,55],['36 (S)',107,72,57],['38 (M)',112,74,58],['40 (G)',117,76,59],['42 (XL)',122,78,60],['44 (XXL)',127,80,61],['46 (3XL)',132,82,61]] as $row)<tr class="border-b border-line"><td class="py-5 font-medium">{{ $row[0] }}</td><td>{{ $row[1] }}</td><td>{{ $row[2] }}</td><td>{{ $row[3] }}</td></tr>@endforeach</tbody></table><p class="mt-5 text-xs leading-5 text-muted">Medidas en centímetros. Puede existir una variación aproximada de 1 cm.</p></div></div>
    </div>
    <div x-cloak x-show="tab==='vestidos'" x-transition.opacity class="pt-12">
        <div class="grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><p class="eyebrow">Cómo medir</p><h2 class="display-md mt-4">Vestidos</h2><div class="mt-10"><img src="{{ asset('images/editorial/guia_vestido.png') }}" alt="Guía de medidas para vestidos" class="mx-auto w-full max-w-sm" loading="lazy"></div></div>
        <div class="overflow-x-auto"><table class="w-full min-w-[520px] text-center text-sm"><thead class="border-b border-ink text-[10px] uppercase tracking-[.14em]"><tr><th class="py-4 text-left">Medida</th><th>CH</th><th>M</th><th>G</th><th>XG</th></tr></thead><tbody>@foreach([['A',83,89,95,95],['B',92,104,112,124],['C',84,96,108,120],['D',94,106,116,132],['E',36,42,48,53]] as $row)<tr class="border-b border-line"><td class="py-6 text-left font-medium">{{ $row[0] }}</td><td>{{ $row[1] }}</td><td>{{ $row[2] }}</td><td>{{ $row[3] }}</td><td>{{ $row[4] }}</td></tr>@endforeach</tbody></table><p class="mt-5 text-xs text-muted">Medidas en centímetros.</p></div></div>
    </div>
    <div x-cloak x-show="tab==='pantalones'" x-transition.opacity class="pt-12">
        <div class="grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><p class="eyebrow">Cómo medir</p><h2 class="display-md mt-4">Pantalones</h2><div class="mt-10"><img src="{{ asset('images/editorial/guia_pantalon.png') }}" alt="Guía de medidas para pantalones" class="mx-auto w-full max-w-sm" loading="lazy"></div></div>
        <div class="overflow-x-auto"><table class="w-full min-w-[620px] text-center text-sm"><tbody>@foreach([['Talla',30,32,34,36,38,40,42],['Cintura',32,34,36,38,39,41,44],['Tiro',26,27,28,29,31,32,33],['Cadera',46,48,50,52,54,56,58]] as $row)<tr class="border-b border-line first:border-t first:border-ink"><th class="py-6 text-left text-[10px] uppercase tracking-[.14em]">{{ $row[0] }}</th>@foreach(array_slice($row,1) as $value)<td>{{ $value }}</td>@endforeach</tr>@endforeach</tbody></table><p class="mt-5 text-xs text-muted">Medidas de la prenda extendida, en centímetros.</p></div></div>
    </div>
</div></section>
<x-catalog-cta />
@endsection
